### PR TITLE
Rewrite of hassplugin.get_history_api()

### PR DESCRIPTION
**Pull request by rr326**
This replace #1084, but based off dev.

This is basically a rewrite of hassplugin.get_history_api()

I'm certain the old one doesn't work properly. Perhaps the HA functionality has changed. At the very least, days= didn't work. Also it seems like some of the limitations that were written into the AD function are no longer necessary.

I did a rewrite because I knew the old one didn't work, it seemed to have some unnecessary limitations, and it seemed easier to rewrite than make spot changes.

I've been using this for a while and it has worked for me, though admittedly my use cases are slim.

entity_id: str (optional)
days: int (optional). Number of days of data to get, ending now.
start_time: date str (optional) - Can NOT have with "days".
end_time: date str (optional) - Default now.

### CODE REVIEW

**Comment by rr326** [comment]
@Odianosen25 let me know if this needs any work. I think some code may have been updated since I did this. Happy to bring it up to speed.

**Comment by Odianosen25** [comment]
Well @rr326 I was going to say you should rebase it so it passes it checks, but in the process of testing, already done all that.

Will be pushing a PR against this branch so you merge and it fixes it all and we can merge this into dev.

regards

**Comment by rr326** [comment]
@Odianosen25 ok - just let me know if and what you need me to do.

**Comment by Odianosen25** [comment]
I have created a PR against your branch which rebases it and hopefully allow it to pass the checks.

DO merge and we can continue.

Regards

**Review by Odianosen25 — APPROVED** [review]

**Comment by Odianosen25** [comment]
@rr326 hello,

I am still awaiting some response from you pls.

regards

**Comment by rr326** [comment]
@Odianosen25 I’m sorry - I didn’t realize you needed something from me. I’m still not sure what   

Testing that it works?

If so I will do this am - meetings first then this.

**Comment by Odianosen25** [comment]
@rr326,

Yeah I tested it and it works. But since your checks failed, I made a PR against your main branch so you merge it to your code and it should allow your checks to pass here.

Once it passes here, I can then merge it. I will send you a message on your branch, so you merge my PR.

Regards

**Comment by rr326** [comment]
Oh - I didn’t understand that’s how it works. Sorry to be a roadblock. Will
do as soon as I can. Couple hours ...

**Comment by Odianosen25** [comment]
@rr326,

Ah silly me, the PR I made was against your dev and not the branch that has this PR. So even when you had merged it, its still not passing the checks.

You will need to rebase your code. Just try the following in your local directory

```
git checkout dev
git pull
git checkout dev_hassplugin_get_history_api
git rebase dev
<fix any errors that might come up>
git push -u origin dev_hassplugin_get_history_api
```

The steps above should fix your issue.
On the other hand, since you had merged my PR against your dev, as that should now be in line with the latest dev,  just use that one and make a new PR and that should pass the checks.

If it works then you can close this one; apologies for the extra stress.

Regards

**Comment by Odianosen25** [comment]
Ok @rr326, with the rebase you did, I was able to finally run the checks on it locally, so should all be fixed now.

Kindly merge and that should clear it all.

Regards

**Pull request merged**
