### PR TITLE
update material design icons to v5.4.55

### PR DESCRIPTION
**Pull request by thomasdelaet**
use latest version of material design icons

### CODE REVIEW

**Comment by Odianosen25** [comment]
Hello @thomasdelaet,

Please can you rebase your PR?

Thanks

**Comment by thomasdelaet** [comment]
done

**Comment by Odianosen25** [comment]
Many thanks @thomasdelaet,

Please can you run the pre-commit checks on it so it can pass the checks?

Regards

**Comment by thomasdelaet** [comment]
should be okay now

**Pull request merged**
