### PR TITLE
Fix #1176 TypeError

### LINKED ISSUE #1176: TypeError: a bytes-like object is required, not 'str'
When I build and run (`docker build -t appdaemon:dev . && docker run appdaemon:dev`) the `dev` branch, the app exits with errors.

```
2021-02-21 10:25:51.952206 INFO AppDaemon: AppDaemon Version 4.0.6 starting
2021-02-21 10:25:51.953718 INFO AppDaemon: Python version is 3.8.8
2021-02-21 10:25:51.953840 INFO AppDaemon: Configuration read from: /conf/appdaemon.yaml
2021-02-21 10:25:51.954030 INFO AppDaemon: Added log: AppDaemon
2021-02-21 10:25:51.954185 INFO AppDaemon: Added log: Error
2021-02-21 10:25:51.954361 INFO AppDaemon: Added log: Access
2021-02-21 10:25:51.954522 INFO AppDaemon: Added log: Diag
2021-02-21 10:25:52.012170 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2021-02-21 10:25:52.163496 INFO HASS: HASS Plugin Initializing
2021-02-21 10:25:52.187159 INFO HASS: HASS Plugin initialization complete
2021-02-21 10:25:52.187854 INFO AppDaemon: Initializing HTTP
2021-02-21 10:25:52.188573 INFO AppDaemon: Using 'ws' for event stream
2021-02-21 10:25:52.194850 WARNING AppDaemon: ------------------------------------------------------------
2021-02-21 10:25:52.195216 WARNING AppDaemon: Unexpected error in HTTP module
2021-02-21 10:25:52.195461 WARNING AppDaemon: ------------------------------------------------------------
2021-02-21 10:25:52.210179 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/http.py", line 171, in __init__
    net = url.netloc.split(":")
TypeError: a bytes-like object is required, not 'str'
...
...
...
2021-02-21 10:25:52.454334 WARNING AppDaemon: ------------------------------------------------------------
2021-02-21 10:25:52.455067 INFO AppDaemon: Previous message repeated 1 times
2021-02-21 10:25:52.455230 WARNING AppDaemon: Unexpected error during process_event()
2021-02-21 10:25:52.455544 WARNING AppDaemon: ------------------------------------------------------------
2021-02-21 10:25:52.455861 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/events.py", line 235, in process_event
    await self.AD.http.stream_update(namespace, mydata)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/http.py", line 699, in stream_update
    self.AD.thread_async.call_async_no_wait(self.stream.process_event, data)
AttributeError: 'HTTP' object has no attribute 'stream'

2021-02-21 10:25:52.456080 WARNING AppDaemon: ------------------------------------------------------------
2021-02-21 10:25:52.462482 WARNING AppDaemon: ------------------------------------------------------------
2021-02-21 10:25:52.462707 WARNING AppDaemon: Unexpected error during run()
2021-02-21 10:25:52.462910 WARNING AppDaemon: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/__main__.py", line 149, in run
    loop.run_until_complete(asyncio.gather(*pending))
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/appdaemon/admin_loop.py", line 18, in loop
    if self.AD.http.stats_update != "none" and self.AD.sched is not None:
AttributeError: 'HTTP' object has no attribute 'stats_update'
2021-02-21 10:25:52.467563 INFO AppDaemon: Previous message repeated 1 times
2021-02-21 10:25:52.468898 INFO AppDaemon: AppDaemon Exited
```

### PR DESCRIPTION
**Pull request by wernerhp**

### CODE REVIEW

**Comment by Odianosen25** [comment]
Hello @wernerhp,

This actually breaks AD when the url is given. I think I will just go with outputting a friendly message for it to be entered, than merging this. Can you please provide a PR for that, or change this?

Regards

**Comment by wernerhp** [comment]
🤔 
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

appdaemon/http.py:106:5: C901 'HTTP.__init__' is too complex (19)

##[error]Bash exited with code '1'.
```

**Comment by wernerhp** [comment]
Ok, too many nested ifs in the `__init__` func.  Come to think of it, why do we even get this far if I don't have an `appdaemon.yaml` file at all?  Guessing it should fail when it checks if the file exists...

**Comment by wernerhp** [comment]
Weird that it passes the flake8 complexity check locally...

**Comment by Odianosen25** [comment]
We recently changed the azure python packages and know not if it anything to do with it

**Comment by wernerhp** [comment]
After some debugging I figured out that I had `pre-commit               1.21.0` installed and not `pre-commit             2.10.1`
After re-installing it I get the same errors locally.  (Always exciting when you get the right error 😆 )

**Comment by wernerhp** [comment]
Seems like adding any `if` statement will increase the complexity of the func, or is there a way to add this check without raising complexity? 
https://www.flake8rules.com/rules/C901.html

**Comment by wernerhp** [comment]
Solution...a quick refactor.

**Comment by Odianosen25** [comment]
I don’t have an issue with with this refactoring, but this will need @acockburn’s approval before I can merge this.

regards

**Review by acockburn — APPROVED** [review]

**Pull request merged**
