### PR TITLE
Improve packaging of application

### LINKED ISSUE #1657: Improve packaging system
The `requirements.txt` file is used in a bit confusing way. It it usual practice for this file to contain all the dependencies present in the project virtualenv, created using `pip freeze > requirements.txt`, so that the virtualenv can be easily re-created by any developer locally using `pip install -r requirements.txt.`
But this file is also used as the `install_requires` inside `setup.py`, creating a bit of a conflict.
If one installs the appdaemon locally with `pip install .`, then run `pip freeze > requirements.txt`, the `requirements.txt` file is modified, since all the transitive dependencies are also loaded, as is expected. So the question is: shouldn't the declaration of the project dependencies be moved in a more appropriate place, separate from `requirements.txt`?

## Proposed solution
I propose to more crealry declare the project dependencies, by upgrading the way we use the Python packaging system.
At the moment the package is created from the `setup.py`, read by `setuptools` when building the package.
The way to package applications has changed a lot over the years. Nowadays if one were to follow the official [Python packaging guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/), the recommended setup is to use a `pyproject.toml` to describe all the metadata of the project, including the build tool and the project dependencies.
I suggest we move from the current `setup.py` to a more modern and "standard" solution, by migrating to a `pyproject.toml` file to contain all the project dependencies.

### PR DESCRIPTION
**Pull request by mion00**
Fixes #1657

## Description
- Describe project metadata in `pyproject.toml`
- Remove `requirements.txt`: dependencies are now part of the `pyproject.toml` metadata
- Remove `setup.py`: the recommended way to package a Python application is via a `build-system` configured as part of the  `pyproject.toml`. 
- Define development dependencies under optional `dev` group
  - Can be installed by `pip install .[dev]` (the `[ ]` part specifies a package [extras](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-extras), a variant of the package with additional dependencies. In this case, the development dependencies)
- Update development documentation with instructions on how to setup a local development environment and publish a Python package
- Link development documentation from README for ease of access
- Update Github pipeline to use the new installation method instead of `requirements.txt`

### CODE REVIEW

**Comment by acockburn** [comment]
This looks great - very pleased that you updated the docs too, I compliment you on your thoroughness! I'll merge this shortly, then I will need to figure out how to build for PyPi but that shouldn't be a big deal, and is not urgent.

**Comment by mion00** [comment]
> This looks great - very pleased that you updated the docs too, I compliment you on your thoroughness! I'll merge this shortly, then I will need to figure out how to build for PyPi but that shouldn't be a big deal, and is not urgent.

I added a section in the docs explaining just that! :wink: 
The next logical step is automating the PyPi build as part of the CI, so event that part is out can be out the equation.
Since this might seems a big change in the build process, let me know if anything breaks, and if I can be of help.

**Comment by acockburn** [comment]
Haha, I missed that - it's not always easy to see everything from the deltas that GitHub serves up. But it's merged so I'll go read it now - thanks.

Automating the PyPi build would be cool, didn't know that was possible, but of course it is :)

I usually only update PyPi for actual releases, although I occasionally put out a beta. So, this isn't a huge change, it just cuts out a manual step once per release. I always tag releases, so the rule could be based on that. I have also just decided to start properly using GitHub's release feature - I know that too is based on tags, does that make any difference?

**Comment by mion00** [comment]
I think we can approach the situation from both angles: Github Actions supports triggering from both tags and release, so we can decide what is the preferred way:
- manually create a git tag, push the tag -> automatic build and release on PyPi -> automatic creation of a `release` in Github

- manually create a git tag, push the tag, then
   - manually create a Github release ->  triggers a build and release on PyPi

Of course there could be subtle differences in one approach over the other, I am just brainstorming some possible ideas. Depends also on the solution proposed by https://github.com/AppDaemon/appdaemon/issues/1646#issuecomment-1445440644 about automatic release notes, that _Release Drafter_ is something new also for me.

**Comment by acockburn** [comment]
Interesting. I think my preferred workflow would be to create the TAG manually, Create the release from the tag then have PyPi generation just happen.

Reason is, I will be wanting to add comments to the release, and also we manually keep a history file up to date which is a little more informative than just listing the PRs, so I would like to manually include that as part of the release along with my comments, then finally add all the PRs etc. at the bottom. That would be ideal for me I think.

**Pull request merged**
