### PR TITLE
fixing typo on navigate widget

### PR DESCRIPTION
**Pull request by clyra**
fixing a typo on navigate widget and cosmetic changes to documentation.

### CODE REVIEW

**Comment by clyra** [comment]
Yes and no... I took a lot of tries to understand why the PR was failing in the tests. After that I also got the PRs from the dependabot. Anyway, I will cancel the PR, rebase my repo and submit again.  The main fix is just to change current_dash.lenght to current_dash.length !

**Comment by Odianosen25** [comment]
Pls what's up with this PR? It got conflicts and are we good with the changes?

**Comment by acockburn** [comment]
closing - please re-submit with a clean history

**Comment by clyra** [comment]
the important thing was a line where i wrote current_dash.lenght instead of current_dash.length. Somehow it is correct in the current appdaemon branch. So yeah, discard this PR :-).

**Pull request closed without merging**
