### PR TITLE
fix: Add new required conf options to startup script

### PR DESCRIPTION
**Pull request by alexdor**
Add missing configuration options to the example configuration file and to the startup script for the docker container

### CODE REVIEW

**Comment by alexdor** [comment]
@acockburn let me know if you would prefer another way or if you want any changes

**Comment by onedr0p** [comment]
@acockburn any chance of this getting merged? I am working on a Helm chart that could use this...

https://github.com/k8s-at-home/charts/pull/326

**Review by onedr0p — APPROVED** [review]

**Comment by Odianosen25** [comment]
@onedr0p,

Please I understand this has taken a while, but can you kindly rebase this and I will have it merged.

Regards

**Comment by alexdor** [comment]
@Odianosen25 I think you wanted to tag me 😅 I've rebased the pr : )

**Comment by benleb** [comment]
😂😂👍

**Comment by Odianosen25** [comment]
Ah crap apologies @onedr0p, and thanks for getting it done regardless @alexdor.

regards

**Comment by onedr0p** [comment]
Thanks for merging! Looking forward to a new release 🤙

**Pull request merged**
