### PR TITLE
Hassplugin get_history_api()

### PR DESCRIPTION
**Pull request by rr326**
This is basically a rewrite of `hassplugin.get_history_api()`

I'm certain the old one doesn't work properly. Perhaps the HA functionality has changed.  At the very least, `days=`  didn't work. Also it seems like some of the limitations that were written into the AD function are no longer necessary.

I did a rewrite because I knew the old one didn't work, it seemed to have some unnecessary limitations, and it seemed easier to rewrite than make spot changes. 

I've been using this for a while and it has worked for me, though admittedly my use cases are slim.

    entity_id: str (optional)
    days: int (optional). Number of days of data to get, ending now.
    start_time: date str (optional) - Can NOT have with "days".
    end_time: date str (optional) - Default now.

### CODE REVIEW

**Comment by Odianosen25** [comment]
Thanks for the PR @rr326, are you saying it has never worked? But as you said, it’s possible some recent changes have been made to HA and so it’s breaking.

Thanks again

**Comment by rr326** [comment]
> are you saying it has never worked? 

I really don't know. In all honesty its been quite a while since I looked at that code and am only now getting to issuing the PR. I seem to recall at the time thinking that there was some complicated logic that was probably caused by some limitations to HA. When I looked at it the code didn't seem to match the current HA api logic. I started to just try to tweak it but it got too complicated and messy, so I just rewrote to implement the current HA spec. 

[HA Rest API](https://developers.home-assistant.io/docs/api/rest/) --> go to `/api/history/period/<timestamp>`

**Comment by rr326** [comment]
Hi - I'm new to PRs so I'm not sure if I did this correctly.

There was a bug in my pushed code. (I had been referencing the function I had modified for debugging purposes. But I removed the orig code, so my debugging code was no an error.) 

I *think* the proper code is properly referenced here but I just wanted to highlight it. Probably unnecessary.

**Comment by Odianosen25** [comment]
Yeah I just looked at the link you said, and it has changed since I updated this side of the code.

Thanks for the PR again.

**Comment by Odianosen25** [comment]
Hello @rr326,

Can you fix the docker side of things, and look into the fact your build is failing?

Regards

**Comment by rr326** [comment]
Done. My bad - very sloppy of me. Sorry.

**Comment by Odianosen25** [comment]
Will be closing this @rr326, so we can focus on the other one, now I am beginning to look into this.

regards

**Pull request closed without merging**
