### PR TITLE
Ignore files starting with dot

### PR DESCRIPTION
**Pull request by Odianosen25**

### CODE REVIEW

**Comment by nottledim** [comment]
No idea what do with that (git skills) but what about .yaml file too (or indeed any file)?

**Comment by Odianosen25** [comment]
I believe Yaml file had been done before (will check), but python wasn't added to the list.

With these new fixes, both hidden folders and python files should be fixed

**Comment by Odianosen25** [comment]
Yes for yaml it had been fixed a long time ago https://github.com/AppDaemon/appdaemon/blob/cf2c57a3d2550128588ba31a7aa48f2f44c079d6/appdaemon/app_management.py#L345

Not sure why we didn't fix that for py

**Comment by nottledim** [comment]
yaml gives a different error so something's changed.

```
2021-01-21 16:09:17.421846 WARNING AppDaemon: ------------------------------------------------------------
2021-01-21 16:09:18.432381 WARNING AppDaemon: ------------------------------------------------------------
2021-01-21 16:09:18.433225 WARNING AppDaemon: Unexpected error:
2021-01-21 16:09:18.433729 WARNING AppDaemon: ------------------------------------------------------------
2021-01-21 16:09:18.434684 WARNING AppDaemon: Traceback (most recent call last):
  File "/home/dick/src/appdaemon/appdaemon/app_management.py", line 543, in check_config
    latest = await utils.run_in_executor(self, self.check_later_app_configs, self.app_config_file_modified)
  File "/home/dick/src/appdaemon/appdaemon/utils.py", line 298, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dick/src/appdaemon/appdaemon/app_management.py", line 480, in check_later_app_configs
    ts = os.path.getmtime(path)
  File "/usr/lib/python3.7/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/dick/tmp/appdaemon/conf/apps/.#notify.yaml'
```

**Comment by Odianosen25** [comment]
Ok it should be fixed now, so just check it out again.

Regards

**Comment by nottledim** [comment]
Sorry, I don't know what to checkout to test it.

**Comment by Odianosen25** [comment]
I just updated the same PR since it hasn't been merged. So do a git pull I think and it should all update, if you have already checked it out already

**Comment by nottledim** [comment]
OK, found it at last.  It all seems to work.  Hooray!

**Comment by Odianosen25** [comment]
Ah that's nice, thanks for testing @nottledim, will merge this update later.

Kind regards

**Comment by nottledim** [comment]
It works well.  Big improvement for me. Thanks again.

**Comment by Odianosen25** [comment]
Tanks for confirming @nottledim

**Pull request merged**
