### PR TITLE
Fix HASS turn_on service with async apps (fixes #848)

### LINKED ISSUE #848: turn_on service not working with async apps
## What did I do
I bumped into an [issue](https://community.home-assistant.io/t/need-help-with-appdaemon-4-and-async/163937) from the community forum that resulted to be the same problem I had recently. Consider the following simple application:

```python
import appdaemon.plugins.hass.hassapi as hass

class Simple(hass.Hass):
    async def toggle(self, light):
        super().toggle(light)

    def initialize(self):
        self.create_task(self.toggle("light.0xccccccfffe995875_light"))
```

## What happened
Next error appears after 10 seconds that the app was initialized
```
2020-01-16 19:27:59.061352 WARNING test5: ------------------------------------------------------------
2020-01-16 19:27:59.062493 WARNING test5: Unexpected error running initialize() for test5
2020-01-16 19:27:59.063452 WARNING test5: ------------------------------------------------------------
2020-01-16 19:27:59.064921 WARNING test5: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
asyncio.exceptions.TimeoutError
2020-01-16 19:27:59.065899 WARNING test5: ------------------------------------------------------------
2020-01-16 19:27:59.072580 WARNING AppDaemon: Excessive time spent in utility loop: 10089.0ms, 10088.0ms in check_app_updates(), 1.0ms in other
```

However, if I remove the `async` keyword, it works. Also, if I change `super().toggle(light)` for `self.call_service("homeassistant/toggle", entity_id=light)` and leaving the `async`, it works.

So the problem is that `self.toggle` does not work with async features. It also does not work with `self.turn_on` and `self.turn_off`.

## What do I expect
I'd expect self.toggle to work with async functions.

### PR DESCRIPTION
**Pull request by oxan**

### CODE REVIEW

**Comment by Hellowlol** [comment]
Why hasn’t this been merged?

**Comment by oxan** [comment]
I don't know, I consider AppDaemon dead for all intents and purposes and have jumped ship to [pyscript](https://github.com/custom-components/pyscript).

**Comment by acockburn** [comment]
Not dead so much as resting due to real life issues ...

**Comment by Hellowlol** [comment]
Will I just wanna thank you for the time you have put in. I hope your issue gets sorted. :) I’ll test the PR and rebase it.

**Comment by acockburn** [comment]
Thanks - there is some merging work going on at the moment just not much active dev work. I'm in the middle of relocating and living in a rental with no home automation, and my job has gotten a lot more busy over the last 6 months. A test and rebase would be very helpful thanks.

**Comment by Odianosen25** [comment]
@oxan,

Please I will be closing this PR in favour of [this](https://github.com/AppDaemon/appdaemon/pull/1131), if you don't mind please.

All credits will still go to you with assistance from @Hellowlol.

Kind Regards

**Pull request closed without merging**
