### PR TITLE
Dash input boolean patch

### PR DESCRIPTION
**Pull request by Odianosen25**
Make use of the `input_boolean` service call and not `homeassistant`

### CODE REVIEW

**Comment by ReneTode** [comment]
why?

**Comment by Odianosen25** [comment]
@ReneTode ,

So it can use the proper domain service calls. This also allows it to be easily used within AD<  when using AD generated input_boolean entities. This affects nothing from a user perspective. But if wanting to use the entity outside HA, without it having the right domain service call, it becomes a nightmare

**Comment by ReneTode** [comment]
more logical then creating all those services in AD is creating a general one.

dont create:
input_boolean/turn_on
switch/turn_on
etc.

but create: 
appdaemon/turn_on

or else you endup recreating every HA service.

**Comment by ReneTode** [comment]
besides that you can also replace it yourself
just copy the yaml file to the custom_widgets dir and change your service to whatever you like.

so no nightmare at all. and also no limitation to HA.

**Pull request closed without merging**
