### PR TITLE
Update scheduler.py

### PR DESCRIPTION
**Pull request by wernerhp**
Fix astral import

### CODE REVIEW

**Comment by Odianosen25** [comment]
What’s the major difference between the previous PR and this? And did you run pre-commit so it passes the checks?

regards

**Comment by Odianosen25** [comment]
@wernerhp can you pls correct the checks?

**Comment by wernerhp** [comment]
Sorry, I made the edit on Github directly.  Will update the PR and fix checks.  

I skipped the `flake8` `pre-commit` hook.  For some reason it fails with
```
appdaemon/scheduler.py:19:26: E999 SyntaxError: invalid syntax
```
which is `ad` in 
```
def __init__(self, ad: AppDaemon):
```

**Comment by wernerhp** [comment]
The previous PR imported `astral` and tried to ini `astral.location.Location`, but this doesn't actually work.  Had to change the import and then also imported the `LocationInfo` type for the passed `tuple`.

**Comment by wernerhp** [comment]
Don't really get why the build is failing 🤔

**Comment by Odianosen25** [comment]
@wernerhp can you separate the PR for scheduler fix from the others? So it’s easier to know what is what?

**Comment by wernerhp** [comment]
> @wernerhp can you separate the PR for scheduler fix from the others? So it’s easier to know what is what?

Yeah, sorry accidentally committed my virtualenv directory.  Fixed now.

**Comment by Odianosen25** [comment]
Thanks but the flake pls make another PR so we can handle it separately.

**Comment by Odianosen25** [comment]
Is the “Location” needed after importing “LocationInfo”?

**Comment by wernerhp** [comment]
Yeah, we are still calling `Location`, that's what we want.  `LocationInfo` was just added to define the `tuple` which is passed as an parameter to `Location`'s constructor.  See [`Location.__init__`](https://github.com/sffjunkie/astral/blob/3282d7b437349bc035c8a7dff5c27ec9997a2cdf/src/astral/location.py#L20)

**Pull request merged**
